COL_WEATHER_DATE = 'date'
COL_WEATHER_TEMP_MEAN = 'tmed'
COL_WEATHER_TEMP_MIN = 'tmin'
COL_WEATHER_TEMP_MAX = 'tmax'
COL_WEATHER_HOUR_TEMP_MAX = 'horatmax'
COL_WEATHER_HOUR_TEMP_MIN = 'horatmin'
COL_WEATHER_WIND_MEAN = 'velmedia'
COL_WEATHER_RAIN = 'prec'

COL_WEATHER_TEMP_HOURLY ='temp'
COL_WEATHER_WIND_HOURLY = 'wind'
COL_WEATHER_RAIN_HOURLY = 'rain'

SUNRISE_HOUR = 7
SUNSET_HOUR = 22