from bicimad.constants.bikes_constants import COL_BIKES_DAY_OF_WEEK, COL_BIKES_WEEKEND, COL_BIKES_RIDES_MEAN_WEEKDAY, \
    COL_BIKES_RIDES
from bicimad.constants.weather_constants import COL_WEATHER_TEMP_MEAN, COL_WEATHER_TEMP_MIN, COL_WEATHER_TEMP_MAX, \
    COL_WEATHER_RAIN, COL_WEATHER_WIND_MEAN


# Daily model

TEST_SIZE = 0.2
CATEGORICAL_COLUMNS_DAILY = [
    COL_BIKES_DAY_OF_WEEK,
    COL_BIKES_WEEKEND
]
# TODO create new set of constants for dataset (using COL_BIKES_* and COL_WEATHER_*)?
NUMERICAL_COLUMNS_DAILY = [
    COL_BIKES_RIDES_MEAN_WEEKDAY,
    COL_WEATHER_TEMP_MEAN,
    COL_WEATHER_TEMP_MIN,
    COL_WEATHER_TEMP_MAX,
    COL_WEATHER_RAIN,
    COL_WEATHER_WIND_MEAN
]
FEATURES = [CATEGORICAL_COLUMNS_DAILY, NUMERICAL_COLUMNS_DAILY]
TARGET = COL_BIKES_RIDES


# Hourly model

